language: python
python:
  - "3.6"
addons:
  firefox: latest
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.23.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install codacy-coverage
  - export CODACY_PROJECT_TOKEN=2e7d245aa66f47a78e90e4b81b450385
  - pip install -r requirements.txt
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/src
before_script: # for Travis
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - pytest src -v  --cov=src --cov-report=term-missing --cov-report=xml --setup-show
after_success:
  - python-codacy-coverage -r coverage.xml
